name: Deploy DB
run-name: Deployment 🚀 on branch ${{ github.head_ref || github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:

jobs:

  deploy-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update helm chart
        env:
          GCR_IMAGE: ghcr.io/${{ github.repository_owner }}
          TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: ./_k8s
        run: |
          until (echo $TOKEN | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin ); do echo "helm login issue, retrying in 10 sec" && sleep 10; done
          helm dependency update
          helm registry logout ${{ env.GCR_IMAGE }}
        shell: bash

      - name: Save chart
        working-directory: ./_k8s
        run: |
          echo folder content
          ls -l
          helm package . --version v0.1


      - name: Push Chart to Dockerhub
        working-directory: ./_k8s
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 
          helm push tta-v0.1.tgz oci://registry-1.docker.io/sarthaknazkani
        shell: bash