{{- include "shared-lib.configmap" . }}
---
{{- include "shared-lib.serviceaccount" . }}
---
{{- include "shared-lib.role" . }}
---
{{- include "shared-lib.rolebinding" . }}
---
{{- include "shared-lib.deployment" . }}
---
{{- include "shared-lib.service" . }}
---
{{- include "shared-lib.secretproviderclass" . }}
